name: paytime

services:
  web:
    container_name: paytime-front
    build:
      context: ./paytime-front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - frontend-network
    volumes:
      - ./paytime-front:/app:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - api

  api:
    container_name: paytime-back
    build:
      context: ./paytime-back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=your-email@example.com
      - SMTP_PASSWORD=your-password
      - MAIL_FROM_NAME=Your App Name
      - MAIL_FROM_ADDRESS=noreply@yourapp.com
      - APP_URL=https://yourapp.com
      - JWT_REFRESH_TIME=${JWT_REFRESH_TIME}
      - JWT_ACCESS_TIME=${JWT_ACCESS_TIME}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./paytime-back:/app:delegated
      - /app/node_modules
    networks:
      - backend-network
      - frontend-network

networks:
  frontend-network:
    name: frontend-network
    driver: bridge
  backend-network:
    name: backend-network
    driver: bridge