name: paytime

services:
  web:
    container_name: paytime-front
    build:
      context: ./paytime-front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - frontend-network
    volumes:
      - ./paytime-front:/app:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - api

  api:
    container_name: paytime-back
    build:
      context: ./paytime-back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_SECURE=${SMTP_SECURE}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - APP_URL=${APP_URL}
      - JWT_REFRESH_TIME=${JWT_REFRESH_TIME}
      - JWT_ACCESS_TIME=${JWT_ACCESS_TIME}
      - JWT_RESET_PASSWORD_TIME=${JWT_RESET_PASSWORD_TIME}
      - JWT_EMAIL_VERIFICATION_TIME=${JWT_EMAIL_VERIFICATION_TIME}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./paytime-back:/app:delegated
      - /app/node_modules
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - redis

  redis:
    container_name: paytime-redis
    image: redis:latest
    ports:
      - "6379:6379" 
    networks:
      - backend-network
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

networks:
  frontend-network:
    name: frontend-network
    driver: bridge
  backend-network:
    name: backend-network
    driver: bridge

volumes:
  redis_data:
