name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Check out the repo
      uses: actions/checkout@v2


    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Install dependencies and run tests for backend
    - name: Install Backend Dependencies
      working-directory: ./paytime-back
      run: npm install

    - name: Run Backend Tests
      working-directory: ./paytime-back
      run: npm test

    # Install dependencies and run tests for frontend
    - name: Install Frontend Dependencies
      working-directory: ./paytime-front
      run: npm install

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push backend
    - name: Build and push Backend
      uses: docker/build-push-action@v6
      with:
        context: ./paytime-back
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/evently:backend

    # Build and push frontend
    - name: Build and push Frontend
      uses: docker/build-push-action@v6
      with:
        context: ./paytime-front
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/evently:frontend 