name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets exist
        run: |
          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "DOCKERHUB_USERNAME is set"
          else
            echo "DOCKERHUB_USERNAME is not set"
            exit 1
          fi
          if [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN is set"
          else
            echo "DOCKERHUB_TOKEN is not set"
            exit 1
          fi

  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./paytime-back
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/paytime:backend
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/paytime:backend
          cache-to: type=inline

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./paytime-front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/paytime:frontend
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/paytime:frontend
          cache-to: type=inline